// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfxGFa2X_sYbCgidc3gBzX_PqhAxZ-mhk',
    appId: '1:723284176886:web:6724e9b7556c80126f61d7',
    messagingSenderId: '723284176886',
    projectId: 'fooddelivery-5a9c6',
    authDomain: 'fooddelivery-5a9c6.firebaseapp.com',
    storageBucket: 'fooddelivery-5a9c6.appspot.com',
    measurementId: 'G-6QFK4YMV28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Nu0p8iQ85986j08WwZNAjcRpwnU55vg',
    appId: '1:723284176886:android:17e3e97289641c5c6f61d7',
    messagingSenderId: '723284176886',
    projectId: 'fooddelivery-5a9c6',
    storageBucket: 'fooddelivery-5a9c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1eP85493KENQTap-Pb91wjpvzQmflbGM',
    appId: '1:723284176886:ios:281cbd2bac158d186f61d7',
    messagingSenderId: '723284176886',
    projectId: 'fooddelivery-5a9c6',
    storageBucket: 'fooddelivery-5a9c6.appspot.com',
    iosClientId: '723284176886-9kjm8vs475pscfn0shir2kev10t096gu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fooddeliveryappyoutube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1eP85493KENQTap-Pb91wjpvzQmflbGM',
    appId: '1:723284176886:ios:281cbd2bac158d186f61d7',
    messagingSenderId: '723284176886',
    projectId: 'fooddelivery-5a9c6',
    storageBucket: 'fooddelivery-5a9c6.appspot.com',
    iosClientId: '723284176886-9kjm8vs475pscfn0shir2kev10t096gu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fooddeliveryappyoutube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsAH5DSoXf_WZjDgOKxuJHH0V3RJ3vPgg',
    appId: '1:723284176886:web:a5c661d0a67dfd016f61d7',
    messagingSenderId: '723284176886',
    projectId: 'fooddelivery-5a9c6',
    authDomain: 'fooddelivery-5a9c6.firebaseapp.com',
    storageBucket: 'fooddelivery-5a9c6.appspot.com',
    measurementId: 'G-D281VEWY2E',
  );

}