// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0p36gvfTAH_qUApx6WzTIS4AcOaKF26o',
    appId: '1:152060704337:web:77381dccc594da8bd5ea70',
    messagingSenderId: '152060704337',
    projectId: 'fooddeliveryapp-4e913',
    authDomain: 'fooddeliveryapp-4e913.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-4e913.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6wiZ3Gietv3tNytGav0rr1fIctgTBiKU',
    appId: '1:152060704337:android:eca2f911693380c3d5ea70',
    messagingSenderId: '152060704337',
    projectId: 'fooddeliveryapp-4e913',
    storageBucket: 'fooddeliveryapp-4e913.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4X9OuliMUk9TbaOr351WGHujPe8YnOBE',
    appId: '1:152060704337:ios:cf2fbab624fda073d5ea70',
    messagingSenderId: '152060704337',
    projectId: 'fooddeliveryapp-4e913',
    storageBucket: 'fooddeliveryapp-4e913.firebasestorage.app',
    iosBundleId: 'com.example.fooddeliveryappyoutube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4X9OuliMUk9TbaOr351WGHujPe8YnOBE',
    appId: '1:152060704337:ios:cf2fbab624fda073d5ea70',
    messagingSenderId: '152060704337',
    projectId: 'fooddeliveryapp-4e913',
    storageBucket: 'fooddeliveryapp-4e913.firebasestorage.app',
    iosBundleId: 'com.example.fooddeliveryappyoutube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0p36gvfTAH_qUApx6WzTIS4AcOaKF26o',
    appId: '1:152060704337:web:99b2ec4ff7c5f22cd5ea70',
    messagingSenderId: '152060704337',
    projectId: 'fooddeliveryapp-4e913',
    authDomain: 'fooddeliveryapp-4e913.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-4e913.firebasestorage.app',
  );

}